# Generated by Django 5.2.3 on 2025-07-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentsmodel',
            table='studentsmodel',
        ),
    ]
